Factory/Models/Machine.cs
using System.Collections.Generic;

namespace Factory.Models
{
  public class Machine
  {
    public Machine()
    {
      this.Technicians = new HashSet<Qualification>();
    }
    public int MachineId { get; set; }
    public string MachineName { get; set; }

    public ICollection<Qualification> Technicians { get; set; }
  }
}

Factory/Controllers/MachinesController.cs
using Factory.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;

namespace Factory.Controllers
{
  public class MachinesController : Controller
  {
    private readonly FactoryContext _db;

    public MachinesController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Machine> model = _db.Machines.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Machine machine)
    {
      _db.Machines.Add(machine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisMachine = _db.Machines
        .Include(machine => machine.Technicians)
        .ThenInclude(join => join.Technician)
        .FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    public ActionResult Edit(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult Edit(Machine machine)
    {
      _db.Entry(machine).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = machine.MachineId});
    }

    public ActionResult Delete(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      _db.Machines.Remove(thisMachine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddTechnician(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      ViewBag.TechnicianId = new SelectList(_db.Technicians, "TechnicianId", "TechnicianName");
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult AddTechnician(Machine machine, int TechnicianId)
    {
      IQueryable<Qualification> qualifications = _db.Qualifications.Where(entry => entry.MachineId == machine.MachineId);
      foreach (Qualification entry in qualifications)
      {
        if (entry.TechnicianId == TechnicianId)
        {
          return RedirectToAction("Details", new { id = machine.MachineId });
        }
      }
      if (TechnicianId != 0)
      {
        _db.Qualifications.Add(new Qualification() { TechnicianId = TechnicianId, MachineId = machine.MachineId });
      }
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = machine.MachineId });
    }

    public ActionResult DeleteTechnician(int id)
    {
      var joinEntry = _db.Qualifications.FirstOrDefault(entry => entry.QualificationId == id);
      ViewBag.Technician = _db.Technicians.FirstOrDefault(technician => technician.TechnicianId == joinEntry.TechnicianId);
      ViewBag.Machine = _db.Machines.FirstOrDefault(machine => machine.MachineId == joinEntry.MachineId);
      return View(joinEntry);
    }

    [HttpPost, ActionName("DeleteTechnician")]
    public ActionResult DeleteTechnicianConfirmed(int id)
    {
      var joinEntry = _db.Qualifications.FirstOrDefault(entry => entry.QualificationId == id);
      _db.Qualifications.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = joinEntry.MachineId });
    }
  }
}

Factory/Controllers/TechniciansController.cs
using Factory.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;

namespace FactoryControllers
{
  public class TechniciansController : Controller
  {
    private readonly FactoryContext _db;

    public TechniciansController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Technician> model = _db.Technicians.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Technician technician)
    {
      _db.Technicians.Add(technician);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisTechnician = _db.Technicians
        .Include(technician => technician.Machines)
        .ThenInclude(join => join.Machine)
        .FirstOrDefault(technician => technician.TechnicianId == id);
      return View(thisTechnician);
    }

    public ActionResult Edit(int id)
    {
      var thisTechnician = _db.Technicians.FirstOrDefault(technician => technician.TechnicianId == id);
      return View(thisTechnician);
    }

    [HttpPost]
    public ActionResult Edit(Technician technician)
    {
      _db.Entry(technician).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = technician.TechnicianId});
    }

    public ActionResult Delete(int id)
    {
      var thisTechnician = _db.Technicians.FirstOrDefault(technician => technician.TechnicianId == id);
      return View(thisTechnician);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisTechnician = _db.Technicians.FirstOrDefault(technician => technician.TechnicianId == id);
      _db.Technicians.Remove(thisTechnician);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddMachine(int id)
    {
      var thisTechnician = _db.Technicians.FirstOrDefault(technician => technician.TechnicianId == id);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "MachineName");
      return View(thisTechnician);
    }

    [HttpPost]
    public ActionResult AddMachine(Technician technician, int MachineId)
    {
      IQueryable<Qualification> qualifications = _db.Qualifications.Where(entry => entry.TechnicianId == technician.TechnicianId);
      foreach (Qualification entry in qualifications)
      {
        if (entry.MachineId == MachineId)
        {
          return RedirectToAction("Details", new { id = technician.TechnicianId });
        }
      }
      if (MachineId != 0)
      {
        _db.Qualifications.Add(new Qualification() { MachineId = MachineId, TechnicianId = technician.TechnicianId });
      }
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = technician.TechnicianId });
    }

    public ActionResult DeleteMachine(int id)
    {
      var joinEntry = _db.Qualifications.FirstOrDefault(entry => entry.QualificationId == id);
      ViewBag.Technician = _db.Technicians.FirstOrDefault(technician => technician.TechnicianId == joinEntry.TechnicianId);
      ViewBag.Machine = _db.Machines.FirstOrDefault(machine => machine.MachineId == joinEntry.MachineId);
      return View(joinEntry);
    }

    [HttpPost, ActionName("DeleteMachine")]
    public ActionResult DeleteMachineConfirmed(int id)
    {
      var joinEntry = _db.Qualifications.FirstOrDefault(entry => entry.QualificationId == id);
      _db.Qualifications.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = joinEntry.TechnicianId });
    }
  }
}

Factory/Views/Machines/AddTechnician.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h3 class="view-title">Dr. Sneuss' Factory</h3>
<hr />
<h4 class="view-title">@Html.Label($"{Model.MachineName}")</h4>
<h4 class="view-title">Add Qualified Technicians</h4>
<div class="flex container">
  @using (@Html.BeginForm())
  {
    @Html.HiddenFor(model => model.MachineId)
    <div class="form-group">
      @Html.Label("Technician")
      @Html.DropDownList("TechnicianId", null, new { @class="form-control" })
    </div>
    <input type="submit" value="Add Qualified Technician" class="btn btn-outline-dark" />
  }
</div>

Factory/Views/Machines/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h3 class="view-title">Dr. Sneuss' Factory</h3>
<hr />
<h4 class="view-title">Add Machine</h4>
<div class="flex container">
  @using (@Html.BeginForm())
  {
    <div class="form-group">
      @Html.Label("Machine Name")
      @Html.TextBoxFor(model => model.MachineName, new {@class="form-control"})
    </div>
    <input type="submit" value="Add Machine" class="btn btn-outline-dark" />
  }
</div>

Factory/Views/Machines/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h3 class="view-title">Dr. Sneuss' Factory</h3>
<hr />
<h4 class="view-title">@Html.Label($"{Model.MachineName}")</h4>
<h4 class="view-title">Remove Machine</h4>
<div class="flex container">
  @using (@Html.BeginForm())
  {
    <h5>Confirm Machine Removal</h5>
    <input type="submit" value="Confirm" class="btn btn-outline-dark" />
  }
</div>

Factory/Views/Machines/DeleteTechnician.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Qualification
@using Factory.Models;

<h3 class="view-title">Dr. Sneuss' Factory</h3>
<hr />
<h4 class="view-title">Remove Qualified Technician</h4>
<h4 class="view-title">@Html.Label($"{ViewBag.Technician.TechnicianName} - {ViewBag.Machine.MachineName}")</h4>
<div class="flex container">
  @using (@Html.BeginForm())
  {
    <h5>Confirm Qualified Technician Removal</h5>
    <input type="submit" value="Confirm" class="btn btn-outline-dark" />
  }
</div>

Factory/Views/Machines/Details.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h3 class="view-title">Dr. Sneuss' Factory</h3>
<hr />
<h4 class="view-title">Machine Details</h4>
<div class="flex container">
  <h4 class="view-title">@Html.Label($"{Model.MachineName}")</h4>
  <h5 class="link">@Html.ActionLink("Edit Machine Details", "Edit", new { id = Model.MachineId })  |  @Html.ActionLink("Remove Machine", "Delete", new { id = Model.MachineId })|@Html.ActionLink("Add Qualified Technician", "AddTechnician", new { id = Model.MachineId })</h5>
  <h5 class="view-title">Qualified Technicians</h5>
  @if (@Model.Technicians.Count == 0)
  {
    <h5>No Qualified Technicians</h5>
  } 
  else
  {
    @foreach(var join in Model.Technicians)
    {
      <h5>@Html.ActionLink($"{join.Technician.TechnicianName}", "Details", "Technicians", new { id = join.Technician.TechnicianId })</h5>
      <h7>@Html.ActionLink("Remove Qualified Technician", "DeleteTechnician", new { id = join.QualificationId })</h7>
      <hr />
    }
  }
</div>

Factory/Views/Machines/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h3 class="view-title">Dr. Sneuss' Factory</h3>
<hr />
<h4 class="view-title">@Html.Label($"{Model.MachineName}")</h4>
<h4 class="view-title">Edit Machine</h4>
<div class="flex container">
  @using (@Html.BeginForm())
  {
    @Html.HiddenFor(model => model.MachineId)
    <div class="form-group">
      @Html.Label("Machine Name")
      @Html.TextBoxFor(model => model.MachineName, new {@class="form-control"})
    </div>
    <input type="submit" value="Apply Changes" class="btn btn-outline-dark" />
  }
</div>

Factory/Views/Machines/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;
@model List<Factory.Models.Machine>;

<h3 class="view-title">Dr. Sneuss' Factory</h3>
<hr />
<h4 class="view-title">Machines</h4>
<h5 class="link">@Html.ActionLink("Add new Machine", "Create")</h5>
<hr />
<div class="flex container">
  @if (Model.Count == 0)
  {
    <h5>None.</h5>
  }
  @foreach (Machine machine in Model)
  {
    <h5 class="link">@Html.ActionLink($"{machine.MachineName}", "Details", new { id = machine.MachineId })</h5>
  }
</div>