Factory/Models/Technician.cs
using System.Collections.Generic;

namespace Factory.Models
{
  public class Technician
  {
    public Technician()
    {
      this.Machines = new HashSet<Qualification>();
    }
    public int TechnicianId { get; set; }
    public string TechnicianName { get; set; }
    public ICollection<Qualification> Machines { get; set; }
  }
}

Factory/Controllers/MachinesController.cs
using Factory.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;

namespace Factory.Controllers
{
  public class MachinesController : Controller
  {
    private readonly FactoryContext _db;

    public MachinesController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Machine> model = _db.Machines.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Machine machine)
    {
      _db.Machines.Add(machine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisMachine = _db.Machines
        .Include(machine => machine.Technicians)
        .ThenInclude(join => join.Technician)
        .FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    public ActionResult Edit(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult Edit(Machine machine)
    {
      _db.Entry(machine).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = machine.MachineId});
    }

    public ActionResult Delete(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      _db.Machines.Remove(thisMachine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddTechnician(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      ViewBag.TechnicianId = new SelectList(_db.Technicians, "TechnicianId", "TechnicianName");
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult AddTechnician(Machine machine, int TechnicianId)
    {
      IQueryable<Qualification> qualifications = _db.Qualifications.Where(entry => entry.MachineId == machine.MachineId);
      foreach (Qualification entry in qualifications)
      {
        if (entry.TechnicianId == TechnicianId)
        {
          return RedirectToAction("Details", new { id = machine.MachineId });
        }
      }
      if (TechnicianId != 0)
      {
        _db.Qualifications.Add(new Qualification() { TechnicianId = TechnicianId, MachineId = machine.MachineId });
      }
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = machine.MachineId });
    }

    public ActionResult DeleteTechnician(int id)
    {
      var joinEntry = _db.Qualifications.FirstOrDefault(entry => entry.QualificationId == id);
      ViewBag.Technician = _db.Technicians.FirstOrDefault(technician => technician.TechnicianId == joinEntry.TechnicianId);
      ViewBag.Machine = _db.Machines.FirstOrDefault(machine => machine.MachineId == joinEntry.MachineId);
      return View(joinEntry);
    }

    [HttpPost, ActionName("DeleteTechnician")]
    public ActionResult DeleteTechnicianConfirmed(int id)
    {
      var joinEntry = _db.Qualifications.FirstOrDefault(entry => entry.QualificationId == id);
      _db.Qualifications.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = joinEntry.MachineId });
    }
  }
}

Factory/Controllers/TechniciansController.cs
using Factory.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;

namespace FactoryControllers
{
  public class TechniciansController : Controller
  {
    private readonly FactoryContext _db;

    public TechniciansController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Technician> model = _db.Technicians.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Technician technician)
    {
      _db.Technicians.Add(technician);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisTechnician = _db.Technicians
        .Include(technician => technician.Machines)
        .ThenInclude(join => join.Machine)
        .FirstOrDefault(technician => technician.TechnicianId == id);
      return View(thisTechnician);
    }

    public ActionResult Edit(int id)
    {
      var thisTechnician = _db.Technicians.FirstOrDefault(technician => technician.TechnicianId == id);
      return View(thisTechnician);
    }

    [HttpPost]
    public ActionResult Edit(Technician technician)
    {
      _db.Entry(technician).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = technician.TechnicianId});
    }

    public ActionResult Delete(int id)
    {
      var thisTechnician = _db.Technicians.FirstOrDefault(technician => technician.TechnicianId == id);
      return View(thisTechnician);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisTechnician = _db.Technicians.FirstOrDefault(technician => technician.TechnicianId == id);
      _db.Technicians.Remove(thisTechnician);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddMachine(int id)
    {
      var thisTechnician = _db.Technicians.FirstOrDefault(technician => technician.TechnicianId == id);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "MachineName");
      return View(thisTechnician);
    }

    [HttpPost]
    public ActionResult AddMachine(Technician technician, int MachineId)
    {
      IQueryable<Qualification> qualifications = _db.Qualifications.Where(entry => entry.TechnicianId == technician.TechnicianId);
      foreach (Qualification entry in qualifications)
      {
        if (entry.MachineId == MachineId)
        {
          return RedirectToAction("Details", new { id = technician.TechnicianId });
        }
      }
      if (MachineId != 0)
      {
        _db.Qualifications.Add(new Qualification() { MachineId = MachineId, TechnicianId = technician.TechnicianId });
      }
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = technician.TechnicianId });
    }

    public ActionResult DeleteMachine(int id)
    {
      var joinEntry = _db.Qualifications.FirstOrDefault(entry => entry.QualificationId == id);
      ViewBag.Technician = _db.Technicians.FirstOrDefault(technician => technician.TechnicianId == joinEntry.TechnicianId);
      ViewBag.Machine = _db.Machines.FirstOrDefault(machine => machine.MachineId == joinEntry.MachineId);
      return View(joinEntry);
    }

    [HttpPost, ActionName("DeleteMachine")]
    public ActionResult DeleteMachineConfirmed(int id)
    {
      var joinEntry = _db.Qualifications.FirstOrDefault(entry => entry.QualificationId == id);
      _db.Qualifications.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = joinEntry.TechnicianId });
    }
  }
}

Factory/Views/Technicians/AddMachine.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Technician

<h3 class="view-title">Dr. Sneuss' Factory</h3>
<hr />
<h4 class="view-title">@Html.Label($"{Model.TechnicianName}")</h4>
<h4 class="view-title">Add Machine Qualifications</h4>
<div class="flex container">
  @using (@Html.BeginForm())
  {
    @Html.HiddenFor(model => model.TechnicianId)
    <div class="form-group">
      @Html.Label("Machine")
      @Html.DropDownList("MachineId", null, new { @class="form-control" })
    </div>
    <input type="submit" value="Add Machine Qualification" class="btn btn-outline-dark" />
  }
</div>

Factory/Views/Technicians/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Technician

<h3 class="view-title">Dr. Sneuss' Factory</h3>
<hr />
<h4 class="view-title">Add Technician</h4>
<div class="flex container">
  @using (@Html.BeginForm())
  {
    <div class="form-group">
      @Html.Label("Technician Name")
      @Html.TextBoxFor(model => model.TechnicianName, new {@class="form-control"})
    </div>
    <input type="submit" value="Add Technician" class="btn btn-outline-dark" />
  }
</div>

Factory/Views/Technicians/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Technician

<h3 class="view-title">Dr. Sneuss' Factory</h3>
<hr />
<h4 class="view-title">@Html.Label($"{Model.TechnicianName}")</h4>
<h4 class="view-title">Remove Technician</h4>
<div class="flex container">
  @using (@Html.BeginForm())
  {
    <h5>Confirm Technician Removal</h5>
    <input type="submit" value="Confirm" class="btn btn-outline-dark" />
  }
</div>

Factory/Views/Technicians/DeleteMachine.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Qualification
@using Factory.Models;

<h3 class="view-title">Dr. Sneuss' Factory</h3>
<hr />
<h4 class="view-title">Remove Qualification</h4>
<h4 class="view-title">@Html.Label($"{ViewBag.Technician.TechnicianName} - {ViewBag.Machine.MachineName}")</h4>
<div class="flex container">
  @using (@Html.BeginForm())
  {
    <h5>Confirm Qualification Removal</h5>
    <input type="submit" value="Confirm" class="btn btn-outline-dark" />
  }
</div>

Factory/Views/Technicians/Details.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Technician

<h3 class="view-title">Dr. Sneuss' Factory</h3>
<hr />
<h4 class="view-title">Technician Details</h4>
<div class="flex container">
  <h4 class="view-title">@Html.Label($"{Model.TechnicianName}")</h4>
  <h5 class="link">@Html.ActionLink("Edit Technician Details", "Edit", new { id = Model.TechnicianId })  |  @Html.ActionLink("Remove Technician", "Delete", new { id = Model.TechnicianId }) | @Html.ActionLink("Add Machine Qualification", "AddMachine", new { id = Model.TechnicianId })</h5>
  <h5 class="view-title">Machine Qualifications</h5>
  @if (@Model.Machines.Count == 0)
  {
    <h5>No Qualifications</h5>
  } 
  else
  {
    @foreach(var join in Model.Machines)
    {
      <h5>@Html.ActionLink($"{join.Machine.MachineName}", "Details", "Machines", new { id = join.Machine.MachineId })</h5>
      <h7>@Html.ActionLink("Remove Qualification", "DeleteMachine", new { id = join.QualificationId })</h7>
      <hr />
    }
  }
</div>

Factory/Views/Technicians/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Technician

<h3 class="view-title">Dr. Sneuss' Factory</h3>
<hr />
<h4 class="view-title">@Html.Label($"{Model.TechnicianName}")</h4>
<h4 class="view-title">Edit Technician</h4>
<div class="flex container">
  @using (@Html.BeginForm())
  {
    @Html.HiddenFor(model => model.TechnicianId)
    <div class="form-group">
      @Html.Label("Technician Name")
      @Html.TextBoxFor(model => model.TechnicianName, new {@class="form-control"})
    </div>
    <input type="submit" value="Apply Changes" class="btn btn-outline-dark" />
  }
</div>

Factory/Views/Technicians/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;
@model List<Factory.Models.Technician>;

<h3 class="view-title">Dr. Sneuss' Factory</h3>
<hr />
<h4 class="view-title">Technicians</h4>
<h5 class="link">@Html.ActionLink("Add new Technician", "Create")</h5>
<hr />
<div class="flex container">
  @if (Model.Count == 0)
  {
    <h5>None.</h5>
  }
  @foreach (Technician technician in Model)
  {
    <h5 class="link">@Html.ActionLink($"{technician.TechnicianName}", "Details", new { id = technician.TechnicianId })</h5>
  }
</div>